import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "FixItNow Frontend App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
      {/* navber */}
        {children}
        {/* footer */}
        </body>
    </html>
  );
}
