import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans, Outfit, Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toast } from "radix-ui";
import { Toaster } from "sonner";
import Navbar from "@/components/shared/navbar";

const outfitHeading = Outfit({subsets:['latin'],variable:'--font-heading'});

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "FixItNow Frontend App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full antialiased", "font-sans", inter.variable, outfitHeading.variable)}
    >
      <body className="min-h-full flex flex-col">
        {/* <Navbar></Navbar> */}
        <Toaster position="top-right"></Toaster>
      {/* navber */}
        {children}
        {/* footer */}
        </body>
    </html>
  );
}
